Removed specific message envelope and unused code
eclipse-kanto/azure-connector pull request #23
Opened 2022-10-11 11:24 UTC by stoyan-zoubev

[#16] Remove specific message format restriction

- deleted specific message envelope and updated command bus handler.
- deleted code that is not used by kanto azure connector binary, e.g. things handlers, protobuf files, message mapper, etc.
- reworked command passthrough handler to be generic so that is does not depend on a certain message format.
- renamed AllowedLocalTopicsList and AllowedCloudMessageTypesList settings to PassthroughTelemetryTopic and PassthroughCommandTopic.
- removed unused MessageMapperConfig setting.

Signed-off-by: Stoyan Zoubev <Stoyan.Zoubev@bosch.io>

2022-10-11 12:11 UTC, hristobojilov approved these changes

2022-10-12 08:41 UTC, e-grigorov requested changes

2022-10-12 08:41 UTC, e-grigorov commented on flags/flags.go
> +// Add adds the Cloud Agent flags and uses the provided settings to collect the provided values.
- Cloud Agent -> azure connector
- `provided` is duplicated, the wording can be polished a little

2022-10-12 08:41 UTC, e-grigorov commented on config/settings.go
> +	PassthroughCommandTopic   string `json:"passthroughCommandTopic"`
- the name should be: ...Topics
- the type should be string[] - we already have such examples in suite bootstrapping and software update components

2022-10-12 08:41 UTC, e-grigorov commented on flags/flags.go
> +		"The list of passthrough telemetry topics the cloud agent listens to.",
- cloud agent -> azure connector
- the description can clarify that these are local topics
- full stop is not used in the end of these flag descriptions

2022-10-12 08:41 UTC, e-grigorov commented on flags/flags.go
> +		"ID Scope from Azure Device Provisioning Service",
- ID Scope -> ID scope
- Azure Device Provisioning Service -> Azure Device Provisioning service
- `from` - I guess that it's `for`

2022-10-12 08:41 UTC, e-grigorov commented on flags/flags.go
> +		"The passthrough command topic where all messages from the cloud are forwarded to.",
- the description can clarify that these are local topics
- full stop is not used in the end of these flag descriptions

2022-10-12 08:41 UTC, e-grigorov commented on flags/flags.go
> +// Copy configured all set flag values to map.
configured all set flag values to map -> copies all configured...

2022-10-12 08:41 UTC, e-grigorov commented on go.mod
> -	github.com/golang/protobuf v1.4.2 // indirect
General note, I guess that the notice file has to be updated.

2022-10-12 08:41 UTC, e-grigorov commented on routing/bus/command.go
> +		if msg, err := commandHandler.HandleMessage(msg); err == nil {
The error is ignored but should not be.

2022-10-12 08:41 UTC, e-grigorov commented on routing/message/handlers/command/passthrough_handler.go
> +// TODO: to be extended in the future as part of issue #21
Clean up this TODO, if required, it can be put as a comment to the related ticket.

2022-10-12 13:57 UTC, e-grigorov commented on resources/config.json
>      "cacert": "/etc/azure-connector/iothub.crt",
Could you please fix it to caCert?

2022-10-12 14:56 UTC, merged